### ISSUE TITLE
Why another one?

### ISSUE THREAD

**Issue by escamoteur** [sameerkapps/MvvmAtom#1]
Hi Sameer.
just wondering why yu started just another MVVM framework? What does it offer new?
Beeing a contributor to xamvvm I would be happe if we perhaps could join forces.
All the best
Thomas

**Comment by sameerkapps** [comment]
Thanks for taking a look at my code. Each MVVM framework has its own flavor. MvvmAtom provides the most needed functionality with a minimum number of classes. That makes it easy to learn and faster in performance. It also provides specialization that allows commands to make a decision based on any property change in the view model.
